# Generated by Django 4.2.9 on 2024-03-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRating',
            fields=[
                ('AgeRatingid', models.AutoField(primary_key=True, serialize=False)),
                ('AgeRating', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'AgeRating',
                'verbose_name_plural': 'AgeRatings',
                'db_table': 'AgeRating',
                'ordering': ['AgeRating'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GenreCategory',
            fields=[
                ('GenreCategoryid', models.AutoField(primary_key=True, serialize=False)),
                ('GenreCategory', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'GenreCategory',
                'verbose_name_plural': 'GenreCategories',
                'db_table': 'GenreCategory',
                'ordering': ['GenreCategory'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NumberofPlayers',
            fields=[
                ('NumberofPlayersid', models.AutoField(primary_key=True, serialize=False)),
                ('NumberofPlayers', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'NumberofPlayers',
                'verbose_name_plural': 'NumberofPlayers',
                'db_table': 'NumberofPlayers',
                'ordering': ['NumberofPlayers'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PopularityRating',
            fields=[
                ('PopularityRatingid', models.AutoField(primary_key=True, serialize=False)),
                ('PopularityRating', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'PopularityRating',
                'verbose_name_plural': 'PopularityRatings',
                'db_table': 'PopularityRating',
                'ordering': ['PopularityRating'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VideoGames',
            fields=[
                ('VideoGamesid', models.AutoField(primary_key=True, serialize=False)),
                ('VideoGameName', models.CharField(max_length=255, unique=True)),
                ('Description', models.CharField(max_length=255)),
                ('YoutubeTrailerLink', models.CharField(max_length=255)),
                ('PC_Windows', models.CharField(max_length=1)),
                ('PC_MAC', models.CharField(max_length=1)),
                ('Playstation', models.CharField(max_length=1)),
                ('NintendoSwitch', models.CharField(max_length=1)),
                ('Xbox', models.CharField(max_length=1)),
                ('Phone_Android', models.CharField(max_length=1)),
                ('Phone_iPhone', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'VideoGame',
                'verbose_name_plural': 'VideoGames',
                'db_table': 'VideoGames',
                'ordering': ['VideoGamesid'],
                'managed': False,
            },
        ),
    ]
