# Generated by Django 4.2.9 on 2024-03-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_agerating_genrecategory_numberofplayers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agerating',
            options={'managed': False, 'ordering': ['AgeRatingID'], 'verbose_name': 'AgeRating', 'verbose_name_plural': 'AgeRatings'},
        ),
        migrations.AlterModelOptions(
            name='numberofplayers',
            options={'managed': False, 'ordering': ['NumberofPlayersID'], 'verbose_name': 'NumberofPlayers', 'verbose_name_plural': 'NumberofPlayers'},
        ),
        migrations.AlterModelOptions(
            name='popularityrating',
            options={'managed': False, 'ordering': ['PopularityRatingID'], 'verbose_name': 'PopularityRating', 'verbose_name_plural': 'PopularityRatings'},
        ),
        migrations.AlterModelOptions(
            name='videogames',
            options={'managed': False, 'ordering': ['VideoGameID'], 'verbose_name': 'VideoGame', 'verbose_name_plural': 'VideoGames'},
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
